src/core/urls.py
from django.conf.urls import include, url
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView

urlpatterns = [

    url(r'^register/$',
        RegistrationView.as_view(form_class=RegistrationFormUniqueEmail),
        name='registration_register'),

    url(r'', include('registration.backends.hmac.urls')),

]

src/customers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # customer
    url(r'^add/$', views.CustomerEditView.as_view(),
        name='customer_add'),
    url(r'^$', views.CustomerListView.as_view(), name='customer_list'),
    url(r'^$', views.CustomerListView.as_view(), name='index'),  # homeme
    url(r'^(?P<pk>[\w-]+)/$', views.customer, name='customer'),
    url(r'^(?P<pk>[\w-]+)/edit/$',
        views.CustomerEditView.as_view(),
        name='customer_edit'),


]

src/customers/models.py
from django.db import models
from utilities.utils import csv_format
from utilities.models import DateTimedModel
from django.utils.translation import ugettext as _
from django.db.models import Sum
import invoices
import payments
from django.urls import reverse


class Customer(DateTimedModel):
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    cid = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    post_pay = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Customer')

    def to_csv(self):
        return csv_format([
            self.name,
            self.cid,
            self.address,
        ])

    def get_absolute_url(self):
        return reverse('customer', args=[self.pk])

    @property
    def total_sales(self):
        return self.sale_set.all().aggregate(
            Sum('total_value'))['total_value__sum'] or 0

    @property
    def total_payments(self):
        return payments.models.Payment.objects.filter(
            sale__in=self.sale_set.all()).aggregate(
            Sum('total_value'))['total_value__sum'] or 0

    @property
    def total_invoices(self):
        return invoices.models.Invoice.objects.filter(
            sale__in=self.sale_set.all()).aggregate(
            Sum('total_value'))['total_value__sum'] or 0

    @property
    def count_sales_invoices_pending(self):
        return invoices.models.Invoice.sales_pending_by_customer(self).count()

    @property
    def count_sales_payments_pending(self):
        return payments.models.Payment.sales_pending_by_customer(self).count()

src/invoices/models.py
from django.db import models
from utilities.models import DateTimedModel
from sales.models import Sale
from django.utils.translation import ugettext as _
from django.db.models import OuterRef, Subquery, Sum, Q
from django.db.models.functions import Coalesce


class Invoice(DateTimedModel):
    internal_id = models.CharField(max_length=100)
    sale = models.ForeignKey(Sale)
    total_value = models.DecimalField(
        u'Total Value', default=0, null=True,
        max_digits=10, decimal_places=3)

    date_to_pay = models.DateField()
    date_issue = models.DateField()

    notes = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = _('Invoice')

    def __unicode__(self):
        return "{}".format(self.internal_id)

    def __str__(self):
        return "{}".format(self.internal_id)

    def __get_sales_pending(customer=None):
        invoices = Invoice.objects.filter(sale=OuterRef('pk')).values('sale')
        sum_invoices = invoices.annotate(
            sum=Coalesce(Sum('total_value'), 0)).values('sum')

        q_filter = Q(total_value__gt=Coalesce(Subquery(sum_invoices), 0))
        if customer:
            q_filter &= Q(customer=customer)

        return Sale.objects.filter(q_filter)

    @staticmethod
    def sales_pending_by_customer(customer):
        return Invoice.__get_sales_pending(customer)

    @staticmethod
    def sales_pending():
        return Invoice.__get_sales_pending()

src/payments/models.py
from django.db import models
from utilities.models import DateTimedModel
from sales.models import Sale
from django.utils.translation import ugettext as _
from django.db.models import OuterRef, Subquery, Sum, Q
from django.db.models.functions import Coalesce


class Payment(DateTimedModel):
    sale = models.ForeignKey(Sale)
    total_value = models.DecimalField(
        u'Total Value', default=0, null=True,
        max_digits=10, decimal_places=3)

    pay_at = models.DateField()
    notes = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = _('Payment')

    def __str__(self):
        return "{}".format(self.id)

    def __get_sales_pending(customer=None):
        payments = Payment.objects.filter(sale=OuterRef('pk')).values('sale')
        sum_payments = payments.annotate(
            sum=Coalesce(Sum('total_value'), 0)).values('sum')

        q_filter = Q(total_value__gt=Coalesce(Subquery(sum_payments), 0))
        if customer:
            q_filter &= Q(customer=customer)

        return Sale.objects.filter(q_filter)

    @staticmethod
    def sales_pending_by_customer(customer):
        return Payment.__get_sales_pending(customer)

    @staticmethod
    def sales_pending():
        return Payment.__get_sales_pending()

src/sales/models.py
from django.db import models
from utilities.models import DateTimedModel
from customers.models import Customer
from django.db.models import Sum
from django.utils.translation import ugettext as _
from utilities.utils import csv_format
from django.urls import reverse


class Sale(DateTimedModel):
    internal_id = models.CharField(max_length=100)
    customer = models.ForeignKey(Customer)
    total_value = models.DecimalField(
        u'Total Value', default=0, null=True,
        max_digits=10, decimal_places=3)

    done_at = models.DateField()
    concept = models.CharField(max_length=100)
    notes = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return "{} / {} ".format(self.internal_id, self.customer)

    def __str__(self):
        return "{} / {} ".format(self.internal_id, self.customer)

    def to_csv(self):
        return csv_format([
            self.internal_id,
            self.customer,
            self.total_value,
            self.done_at,
            self.notes,
            self.total_invoices,
            self.total_payments
        ])

    class Meta:
        verbose_name = _('Sale')

    def get_absolute_url(self):
        return reverse('sale', args=[self.pk])

    @property
    def total_payments(self):
        return self.payment_set.all().aggregate(
            Sum('total_value'))['total_value__sum'] or 0

    @property
    def total_invoices(self):
        return self.invoice_set.all().aggregate(
            Sum('total_value'))['total_value__sum'] or 0

src/customers/forms.py
from django.forms import ModelForm
from customers.models import Customer
from utilities.forms import BootstrapMixin


class CustomerForm(ModelForm, BootstrapMixin):
    class Meta:
        model = Customer
        fields = ['name', 'cid', 'address', 'active']

src/customers/views.py
from django.shortcuts import render
from customers.models import Customer
from customers.forms import CustomerForm
from customers import tables, filters
from utilities.views import ObjectEditView, ObjectListView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404


class CustomerEditView(ObjectEditView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('customer_list')
    template_name = 'customers/add.html'
    cancel_url = 'customer_list'

    def get_object(self, kwargs, request):
        return get_object_or_404(self.model, pk=kwargs['pk'])


class CustomerListView(ObjectListView):
    queryset = Customer.objects.order_by('-id')
    table = tables.CustomerTable
    template_name = 'customers/list.html'
    filter = filters.CustomerFilter

    # Hook filter by request
    def alter_queryset(self, request):
        return self.queryset.all()


def customer(request, pk):
    queryset = Customer.objects.all()
    customer = get_object_or_404(queryset, pk=pk)
    return render(request, 'customers/show.html', {
        'customer': customer,
    })

src/templates/customers/add.html
{% extends 'utilities/obj_edit.html' %}

{% load form_helpers %}
{% load i18n %}


{% block form %}
    <div class="panel panel-default">
        <div class="panel-heading"><strong>{% trans 'Customer' %}</strong></div>
        <div class="panel-body">
            {% render_field form.name %}
            {% render_field form.cid %}
            {% render_field form.address %}
            {% render_field form.active %}
        </div>
    </div>
{% endblock %}

src/templates/customers/list.html
{% extends '_base.html' %}
{% load helpers %}
{% load i18n %}

{% block title %}{% trans 'Customers' %}{% endblock %}

{% block content %}
<div class="pull-right">
    {% if perms.tenancy.add_customer %}
        <a href="{% url 'customer_add' %}" class="btn btn-primary">
            <span class="fa fa-plus" aria-hidden="true"></span>
            {% trans 'Add a customer' %}
        </a>
    {% endif %}
    {% include 'inc/export_button.html' with obj_type='customers' %}
</div>
<h1>{% trans 'Customers' %}</h1>
<div class="row">
    <div class="col-md-9">
        {% include 'utilities/obj_table.html' %}
    </div>
    <div class="col-md-3">
        {% include 'inc/search_panel.html' %}
        {% include 'inc/filter_panel.html' %}
    </div>
</div>
{% endblock %}

src/templates/customers/show.html
{% extends '_base.html' %}
{% load helpers %}
{% load i18n %}
{% load utils_payinv %}

{% block title %}{{ customer }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <ol class="breadcrumb">
            <li><a href="{% url 'customer_list' %}">{% trans 'Customer' %}</a></li>
            <li>{{ customer }}</li>
        </ol>
    </div>
    <div class="col-md-3">
        <form action="{% url 'customer_list' %}" method="get">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="{% trans 'Name' %}" />
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-search" aria-hidden="true"></span>
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="pull-right">
        <a href="{% url 'customer_edit' pk=customer.pk %}" class="btn btn-warning">
            <span class="fa fa-pencil" aria-hidden="true"></span>
            {% trans 'Edit this customer' %}
        </a>
        <a href="{% url 'sale_to_customer' customer_id=customer.pk %}" class="btn btn-success">
            <span class="fa fa-shopping-cart" aria-hidden="true"></span>
            {% trans 'Add sale to this customer' %}
        </a>
</div>

<div class="row">
    <div class="col-md-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                {{ customer }}
            </div>
            <table class="table table-hover panel-body">
                <tr>
                    <td>{% trans 'Name' %}</td>
                    <td>{{ customer.name }}</td>
                </tr>
                <tr>
                    <td>{% trans 'CID' %}</td>
                    <td>{{ customer.cid }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Address' %}</td>
                    <td>{{ customer.address }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Total sales' %}</td>
                    <td>
                        <a href="{% url 'sale_list' %}?customer={{ customer.id }}">
                            {{ customer.total_sales }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>{% trans 'Total invoice' %}</td>
                    <td>
                        <a href="{% url 'invoice_list' %}?customer={{ customer.id }}">
                            {{ customer.total_invoices }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>{% trans 'Total payments' %}</td>
                    <td>
                        <a href="{% url 'payment_list' %}?customer={{ customer.id }}">
                            {{ customer.total_payments }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>{% trans 'Active' %}</td>
                    <td>{{ customer.active|yes_or_no }}</td>
                </tr>
            </table>
        </div>
        {% with customer.custom_fields as custom_fields %}
            {% include 'inc/custom_fields_panel.html' %}
        {% endwith %}
        {% include 'inc/created_updated.html' with obj=customer %}
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans 'Sales Pendings' %}
            </div>
            <table class="table table-hover panel-body">
                <div class="col-md-6 text-center">
                    <h2><a href="{% url 'sale_list_pending_payment' %}?customer={{ customer.id }}" class="btn {% if customer.count_sales_payments_pending %}btn-primary{% else %}btn-default{% endif %} btn-lg">{{ customer.count_sales_payments_pending }}</a></h2>
                    <p>{% trans 'Payments' %}</p>
                </div>

                <div class="col-md-6 text-center">
                    <h2><a href="{% url 'sale_list_pending_invoice' %}?customer={{ customer.id }}" class="btn {% if customer.count_sales_invoices_pending %}btn-primary{% else %}btn-default{% endif %} btn-lg">{{ customer.count_sales_invoices_pending }}</a></h2>
                    <p>{% trans 'Invoices' %}</p>
                </div>
        </div>
    </div>

</div>
{% endblock %}